# Generated by Django 2.1 on 2018-09-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField(default='2000-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=50)),
                ('Costo', models.IntegerField(default='0')),
                ('Disponible', models.IntegerField(default='0')),
                ('num_existencias', models.IntegerField(default='0')),
            ],
        ),
    ]
