# Generated by Django 2.1 on 2018-09-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorias',
        ),
    ]
