# Generated by Django 2.1 on 2018-09-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_categorias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='Costo',
            new_name='costo',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='Disponible',
            new_name='disponible',
        ),
    ]
